---
title: "Reviewer Comparison"
author: "Yishan Guo"
date: "May 25, 2017"
output:
  word_document: default
  html_document: default
---

```{r, echo=F, warning=F, message=F}
rm(list = ls())
library(gemini)
lib.pa()
library(knitr)
dat <- fread("H:/GEMINI/Results/DRM/REDCap/GEMINIDRMTEAM_DATA_2017-05-25_1134.csv")
dat <- dat[order(gemini_id)] %>% filter(!(is.na(date)|date=="")) %>% data.table
```
### Number of patients reviewed by each reviewer
```{r, echo = F,  results = 'asis'}
knitr::kable(dat[,.N, by = ra], table.attr = "style='width:30%;'")
```

### Summary of Variables (number of patients with discrepancy, total N = 18)
```{r, echo = F,  results = 'asis'}
# summary of variables
count.discrep <- function(x){
  apply(x, 2, function(x)length(unique(x)))
}
var_sum <- ddply(dat, ~gemini_id,
                 count.discrep)
var_sum <- cbind(gemini_id = unique(dat$gemini_id),
                 var_sum)
result.sum <- data.table(variable_name = names(var_sum)[9:33],
                    Number_of_patient_with_discrepancy = 
                      apply(var_sum[,9:33], 2, function(x) sum(x>1)))

row.names(result.sum) <- NULL
kable(result.sum)

```


### Summary of Patients (number of variables with discrepancy, total N = 25)
```{r, echo = F,  results = 'asis'}
patient.sum <- data.table(gemini_id = var_sum$gemini_id,
                          Number_of_variables_with_discrepancy = 
                            apply(var_sum[, 9:33], 1, function(x)sum(x>1)))

kable(patient.sum)
```


### Heat Map for Number of Unique Values by Variable and Patient
```{r, echo = F}
# heat map
df <- var_sum[, c(1, 9:33)]
df.long <- melt(df, id.var = "gemini_id")
ggplot(df.long, aes( factor(gemini_id), variable, fill = value)) + 
  geom_tile(aes(fill = value), colour = "white") +
  scale_fill_gradient(low = "white", high = "red") +
  geom_text(aes(label = value)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title = element_blank()) +
  scale_y_discrete(labels = names(df)[2:26])
```
notice that patient 11104039 and patient 11110891 do not have any discrepancy because both of them were only reviewed by one RA.
