---
title: 'Analyses for presentation to hospital administrators'
author: "Yishan Guo"
date: "March 22, 2017"
output: html_document
---
```{r, echo=F, message=F, warning=FALSE}
library(gridExtra)
library(grid)
library(gemini)
lib.pa()
options(scipen = 999)
exclude <- fread("H:/GEMINI/Data/GEMINI/gim.notgim.csv")
cohort <- fread("H:/GEMINI/Results/Ad Hoc/cohort.to.administrators.csv")[!EncID.new%in%exclude$EncID.new]
cohort2 <- fread("H:/GEMINI/Results/Ad Hoc/cohort2.to.administrators.csv")[!EncID.new%in%exclude$EncID.new]

site.map <- data.table(
  code = c("11", "12","13","14","15"),
  site = c("smh", "sbk", "uhn", "msh", "thp")
)
fig1 <- function(dat, title){
  df <- ddply(dat, ~MRP, summarize,
        ave.los = mean(LoS),
        N = length(EncID.new))
  if(title == "Overall"){
    df <- df[df$N>100, ]
  } else{
    df <- df[df$N>20,]
  }
  df <- data.table(df)
  df$code <- str_sub(df$MRP, -2, -1)
  df <- merge(df, site.map, by = "code")
  for(i in c("smh", "sbk", "uhn", "msh", "thp")){
    df[site ==i, mrp := as.numeric(factor(MRP, levels = MRP[order(ave.los, decreasing = T)]))]
  }
  ggplot(df, aes(mrp, ave.los)) + geom_bar(stat = "identity", width = 0.6)+ 
    ggtitle(paste(title, "by MRP", sep = " ")) + 
    facet_grid(. ~site) +
    theme(plot.title = element_text(hjust = 0.5))
}



fig1.2 <- function(dat, title){
  df <- ddply(dat, ~ADMP, summarize,
              ave.los = mean(LoS),
              N = length(EncID.new))
  if(title == "Overall"){
    df <- df[df$N>100, ]
  } else{
    df <- df[df$N>20,]
  }
  df <- data.table(df)
  df$code <- str_sub(df$ADMP, -2, -1)
  df <- merge(df, site.map, by = "code")
  for(i in c("smh", "sbk", "uhn", "msh", "thp")){
    df[site ==i, admp := as.numeric(factor(ADMP, levels = ADMP[order(ave.los, decreasing = T)]))]
  }
  ggplot(df, aes(admp, ave.los)) + geom_bar(stat = "identity", width = 0.6)+ 
    ggtitle(paste(title, "by adm/dis physician", sep = " ")) + 
    facet_grid(. ~site) +
    theme(plot.title = element_text(hjust = 0.5))
}
fig2 <- function(dat, title){
  df <- ddply(dat, ~MRP, summarize,
              ave.cost = mean(Cost, na.rm = T),
              N = length(EncID.new))
  if(title == "Overall"){
    df <- df[df$N>100, ]
  } else{
    df <- df[df$N>20,]
  }
  df <- data.table(df)
  df$code <- str_sub(df$MRP, -2, -1)
  df <- merge(df, site.map, by = "code")
  for(i in c("smh", "sbk", "uhn", "msh", "thp")){
    df[site ==i, mrp := as.numeric(factor(MRP, levels = MRP[order(ave.cost, decreasing = T)]))]
  }
  ggplot(df, aes(mrp, ave.cost)) + geom_bar(stat = "identity", width = 0.6)+ 
    facet_grid(. ~site) + ggtitle(paste(title, "by MRP", sep = " ")) + 
    theme(plot.title = element_text(hjust = 0.5))
}

fig2.2 <- function(dat, title){
  df <- ddply(dat, ~ADMP, summarize,
              ave.cost = mean(Cost, na.rm = T),
              N = length(EncID.new))
  if(title == "Overall"){
    df <- df[df$N>100, ]
  } else{
    df <- df[df$N>20,]
  }
  df <- data.table(df)
  df$code <- str_sub(df$ADMP, -2, -1)
  df <- merge(df, site.map, by = "code")
  for(i in c("smh", "sbk", "uhn", "msh", "thp")){
    df[site ==i, admp := as.numeric(factor(ADMP, levels = ADMP[order(ave.cost, decreasing = T)]))]
  }
  ggplot(df, aes(admp, ave.cost)) + geom_bar(stat = "identity", width = 0.6)+ 
    facet_grid(. ~site) + 
    ggtitle(paste(title, "by adm/dis physician", sep = " ")) + 
    theme(plot.title = element_text(hjust = 0.5))
}
fig3 <- function(dat, title){
  df <- ddply(dat, ~MRP, summarize,
              readmission.rate = mean(read.in.30, na.rm = T),
              ave.los = mean(LoS, na.rm = T),
              N = length(EncID.new))
  if(title == "Overall"){
    df <- df[df$N>100, ]
  } else{
    df <- df[df$N>20,]
  }
  df <- data.table(df)
  df$code <- str_sub(df$MRP, -2, -1)
  df <- merge(df, site.map, by = "code")
  ggplot(df, aes(ave.los, readmission.rate)) + geom_jitter() + 
    ggtitle(paste(title, "by MRP", sep = " ")) + 
    theme(plot.title = element_text(hjust = 0.5)) + facet_grid( .~site)
}



fig3.2 <- function(dat, title){
  df <- ddply(dat, ~ADMP, summarize,
              readmission.rate = mean(read.in.30, na.rm = T),
              ave.los = mean(LoS, na.rm = T),
              N = length(EncID.new))
  if(title == "Overall"){
    df <- df[df$N>100, ]
  } else{
    df <- df[df$N>20,]
  }
  df <- data.table(df)
  df$code <- str_sub(df$ADMP, -2, -1)
  df <- merge(df, site.map, by = "code")
  ggplot(df, aes(ave.los, readmission.rate)) + geom_jitter() + 
    ggtitle(paste(title, "by adm/dis physician", sep = " ")) + 
    theme(plot.title = element_text(hjust = 0.5)) + facet_grid( .~site)
}
fig4 <- function(dat, title){
  df <- ddply(dat, ~MRP, summarize,
              rate.of.inhospital.death = mean(Discharge.Disposition==7, na.rm = T),
              ave.los = mean(LoS, na.rm = T),
              N = length(EncID.new))
  if(title == "Overall"){
    df <- df[df$N>100, ]
  } else{
    df <- df[df$N>20,]
  }
  df <- data.table(df)
  df$code <- str_sub(df$MRP, -2, -1)
  df <- merge(df, site.map, by = "code")
  ggplot(df, aes(ave.los, rate.of.inhospital.death)) + geom_jitter() + 
    ggtitle(paste(title, "by MRP", sep = " ")) + 
    theme(plot.title = element_text(hjust = 0.5)) + facet_grid(.~ site)
}



fig4.2 <- function(dat, title){
  df <- ddply(dat, ~ADMP, summarize,
              rate.of.inhospital.death = mean(Discharge.Disposition==7, na.rm = T),
              ave.los = mean(LoS, na.rm = T),
              N = length(EncID.new))
  if(title == "Overall"){
    df <- df[df$N>100, ]
  } else{
    df <- df[df$N>20,]
  }
  df <- data.table(df)
  df$code <- str_sub(df$ADMP, -2, -1)
  df <- merge(df, site.map, by = "code")
  ggplot(df, aes(ave.los, rate.of.inhospital.death)) + geom_jitter() + 
    ggtitle(paste(title, "by adm/dis physician", sep = " ")) + 
    theme(plot.title = element_text(hjust = 0.5)) + facet_grid(.~ site)
}


```

# Figure 1. Average length-of-stay per doctor


```{r, message=F, echo = F, ,warning=FALSE}
fig1(cohort, "Overall")
fig1.2(cohort2, "Overall")
fig1(cohort[pneumonia==T], "Pneumonia")
fig1.2(cohort2[pneumonia==T], "Pneumonia")
fig1(cohort[chf==T], "CHF")
fig1.2(cohort2[chf==T], "CHF")
fig1(cohort[copd==T], "COPD")
fig1.2(cohort2[copd==T], "COPD")
fig1(cohort[stroke==T], "Stroke")
fig1.2(cohort2[stroke==T], "Stroke")
```







# Figure 2. Average cost per doctor
```{r, message=F, echo = F, ,warning=FALSE}
fig2(cohort, "Overall")
fig2.2(cohort2, "Overall")
fig2(cohort[pneumonia==T], "Pneumonia")
fig2.2(cohort2[pneumonia==T], "Pneumonia")
fig2(cohort[chf==T], "CHF")
fig2.2(cohort2[chf==T], "CHF")
fig2(cohort[copd==T], "COPD")
fig2.2(cohort2[copd==T], "COPD")
fig2(cohort[stroke==T], "Stroke")
fig2.2(cohort2[stroke==T], "Stroke")
```


# Figure 3. Rate of readmission vs average length-of-stay per doctor
```{r, message=F, echo = F, ,warning=FALSE}
fig3(cohort, "Overall")
fig3.2(cohort2, "Overall")
fig3(cohort[pneumonia==T], "Pneumonia")
fig3.2(cohort2[pneumonia==T], "Pneumonia")
fig3(cohort[chf==T], "CHF")
fig3.2(cohort2[chf==T], "CHF")
fig3(cohort[copd==T], "COPD")
fig3.2(cohort2[copd==T], "COPD")
fig3(cohort[stroke==T], "Stroke")
fig1.2(cohort2[stroke==T], "Stroke")
```

# Figure 4. Rate of in-hospital death vs. average length-of-stay per doctor
```{r, message=F, echo = F, ,warning=FALSE}
fig4(cohort, "Overall")
fig4.2(cohort2, "Overall")
fig4(cohort[pneumonia==T], "Pneumonia")
fig4.2(cohort2[pneumonia==T], "Pneumonia")
fig4(cohort[chf==T], "CHF")
fig4.2(cohort2[chf==T], "CHF")
fig4(cohort[copd==T], "COPD")
fig4.2(cohort2[copd==T], "COPD")
fig4(cohort[stroke==T], "Stroke")
fig4.2(cohort2[stroke==T], "Stroke")

```

